### ISSUE TITLE
I see a limited of openCV functions zto play with.

### ISSUE THREAD

**Issue by szaicsek2** [ArthurDelannoyazerty/OpenCV-GUI#5]
Might be my stupidity, but when I launch your GUI front end it stops at showing BLUR and leaves out the - for me  - interesting operations (Threshold etc.)
Reducing the number of operations in the commands file by removeing drawing fucntions does not solve this.  

Stef  (stef.zaicsek@home.nl)

**Comment by ArthurDelannoyazerty** [comment]
Hello,
Yes this is a normal behaviour. These commands are implemented but can only be available when the image have 1 channel (so no RGB, only grayscale). For that, you can use the transformations "COLOR - Colorspace (grayscale)" or "COLOR - Channel".

This availability of certain transformations are based on some condition that you can find in the 'condition' field under each transformation. You can set them to 'True' if you want them to always appear but things might broke.

Hope this help. If you have any questions or criticism, don't hesitate to write them !

**Comment by szaicsek2** [comment]
Thx for your reply. I used your suggestion and it works as expected.

 

Stef
